import type { Account, Proxy, RequestLog, WorkerNode } from "./types";

const t = (minsAgo: number) =>
  new Date(Date.now() - minsAgo * 60_000).toISOString();

export function seedProxies(): Proxy[] {
  return [
    {
      id: "px-tokyo-a",
      name: "Tokyo sticky A",
      type: "http",
      host: "res-jp-a.example.net",
      port: 7777,
      username: "relay-a",
      stickySessionId: "sess-tokyo-a",
      region: "JP-Tokyo",
      status: "active",
      maxAccounts: 6,
      remark: "ChatGPT 组 1",
      createdAt: t(2400),
    },
    {
      id: "px-sg-b",
      name: "Singapore sticky B",
      type: "socks5",
      host: "res-sg-b.example.net",
      port: 1080,
      username: "relay-b",
      stickySessionId: "sess-sg-b",
      region: "SG",
      status: "active",
      maxAccounts: 8,
      remark: "Gemini 出图组",
      createdAt: t(1800),
    },
    {
      id: "px-us-c",
      name: "US West C",
      type: "http",
      host: "res-usw-c.example.net",
      port: 8080,
      username: "relay-c",
      stickySessionId: "sess-us-c",
      region: "US-West",
      status: "disabled",
      maxAccounts: 5,
      remark: "冷却回收",
      createdAt: t(900),
    },
  ];
}

export function seedAccounts(): Account[] {
  return [
    {
      id: "ac-1",
      platform: "chatgpt",
      email: "pool.alpha@mail.test",
      remark: "主对话",
      status: "healthy",
      proxyId: "px-tokyo-a",
      sessionPath: "storage/sessions/ac-1.json",
      failCount: 0,
      totalRequests: 128,
      lastUsedAt: t(8),
      createdAt: t(3200),
    },
    {
      id: "ac-2",
      platform: "chatgpt",
      email: "pool.bravo@mail.test",
      remark: "Vision 备用",
      status: "healthy",
      proxyId: "px-tokyo-a",
      sessionPath: "storage/sessions/ac-2.json",
      failCount: 1,
      totalRequests: 86,
      lastUsedAt: t(22),
      createdAt: t(3000),
    },
    {
      id: "ac-3",
      platform: "chatgpt",
      email: "pool.charlie@mail.test",
      remark: "待登录",
      status: "pending_login",
      proxyId: "px-tokyo-a",
      sessionPath: null,
      failCount: 0,
      totalRequests: 0,
      lastUsedAt: null,
      createdAt: t(40),
    },
    {
      id: "ac-4",
      platform: "chatgpt",
      email: "pool.delta@mail.test",
      remark: "连续失败摘除",
      status: "invalid",
      proxyId: "px-us-c",
      sessionPath: "storage/sessions/ac-4.json",
      failCount: 5,
      totalRequests: 41,
      lastUsedAt: t(180),
      createdAt: t(2100),
    },
    {
      id: "ac-5",
      platform: "gemini",
      email: "img.nova@mail.test",
      remark: "出图主号",
      status: "healthy",
      proxyId: "px-sg-b",
      sessionPath: "storage/sessions/ac-5.json",
      failCount: 0,
      totalRequests: 54,
      lastUsedAt: t(15),
      createdAt: t(2500),
    },
    {
      id: "ac-6",
      platform: "gemini",
      email: "img.orbit@mail.test",
      remark: "冷却中",
      status: "cooling",
      proxyId: "px-sg-b",
      sessionPath: "storage/sessions/ac-6.json",
      failCount: 2,
      totalRequests: 19,
      lastUsedAt: t(12),
      createdAt: t(1400),
    },
    {
      id: "ac-7",
      platform: "gemini",
      email: "img.quill@mail.test",
      remark: "封禁观察",
      status: "banned",
      proxyId: null,
      sessionPath: null,
      failCount: 8,
      totalRequests: 9,
      lastUsedAt: t(900),
      createdAt: t(1600),
    },
    {
      id: "ac-8",
      platform: "chatgpt",
      email: "pool.echo@mail.test",
      remark: "新号",
      status: "pending_login",
      proxyId: null,
      sessionPath: null,
      failCount: 0,
      totalRequests: 0,
      lastUsedAt: null,
      createdAt: t(6),
    },
  ];
}

export function seedLogs(): RequestLog[] {
  return [
    {
      id: "lg-1",
      createdAt: t(8),
      model: "gpt-4o",
      platform: "chatgpt",
      accountId: "ac-1",
      accountEmail: "pool.alpha@mail.test",
      latencyMs: 2140,
      status: "success",
      detail: "对话完成",
      promptPreview: "总结这份规格文档的风险点",
    },
    {
      id: "lg-2",
      createdAt: t(15),
      model: "gemini-image",
      platform: "gemini",
      accountId: "ac-5",
      accountEmail: "img.nova@mail.test",
      latencyMs: 4820,
      status: "success",
      detail: "图片生成完成",
      promptPreview: "雾中的东京车站，电影感",
    },
    {
      id: "lg-3",
      createdAt: t(22),
      model: "gpt-4o",
      platform: "chatgpt",
      accountId: "ac-2",
      accountEmail: "pool.bravo@mail.test",
      latencyMs: 910,
      status: "switched",
      detail: "ac-4 失败后切换",
      promptPreview: "解释 sticky 代理为什么要和账号绑定",
    },
    {
      id: "lg-4",
      createdAt: t(180),
      model: "gpt-4o",
      platform: "chatgpt",
      accountId: "ac-4",
      accountEmail: "pool.delta@mail.test",
      latencyMs: 12000,
      status: "fail",
      detail: "连续失败达到阈值，已摘除",
      promptPreview: "分析这段日志",
    },
  ];
}

export function seedWorkers(): WorkerNode[] {
  return [
    {
      id: "wk-1",
      name: "worker-tokyo-01",
      region: "JP",
      online: true,
      concurrency: 2,
      lastBeat: t(0.2),
    },
    {
      id: "wk-2",
      name: "worker-sg-01",
      region: "SG",
      online: true,
      concurrency: 1,
      lastBeat: t(0.4),
    },
    {
      id: "wk-3",
      name: "worker-usw-01",
      region: "US",
      online: false,
      concurrency: 0,
      lastBeat: t(48),
    },
  ];
}
