import { createFileRoute } from "@tanstack/react-router";
import { Building2, CreditCard, DollarSign, RefreshCw, Scale, Tags } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import { Input, Label } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/commercial")({ component: CommercialPage });

type Snapshot = { tenants: Record<string, unknown>[]; plans: Record<string, unknown>[]; planPeriods: Record<string, unknown>[]; prices: Record<string, unknown>[]; orders: Record<string, unknown>[]; transactions: Record<string, unknown>[]; alerts: Record<string, unknown>[]; paymentEvents: Record<string, unknown>[]; refunds: Record<string, unknown>[]; disputes: Record<string, unknown>[] };

function money(value: unknown, currency: unknown) {
  return new Intl.NumberFormat("zh-CN", { style: "currency", currency: String(currency || "USD") }).format(Number(value || 0) / 100);
}

function CommercialPage() {
  return <AppShell><CommercialView /></AppShell>;
}

function CommercialView() {
  const [data, setData] = useState<Snapshot>({ tenants: [], plans: [], planPeriods: [], prices: [], orders: [], transactions: [], alerts: [], paymentEvents: [], refunds: [], disputes: [] });
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true);
    const response = await fetch("/api/admin/commercial", { credentials: "include" });
    const body = await response.json() as Partial<Snapshot> & { error?: string };
    if (!response.ok) { toast.error(body.error || "商业数据读取失败"); setLoading(false); return; }
    setData({ tenants: body.tenants || [], plans: body.plans || [], planPeriods: body.planPeriods || [], prices: body.prices || [], orders: body.orders || [], transactions: body.transactions || [], alerts: body.alerts || [], paymentEvents: body.paymentEvents || [], refunds: body.refunds || [], disputes: body.disputes || [] });
    setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  const pending = data.orders.filter((order) => order.status === "pending" && order.payment_provider === "manual");
  const stripeOrders = data.orders.filter((order) => order.payment_provider === "stripe").slice(0, 30);
  const balance = data.tenants.reduce((sum, tenant) => sum + Number(tenant.balance_minor || 0), 0);

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-medium">商业运营</h1><p className="mt-1 text-sm text-muted">租户、套餐、官方模型价格、订单和不可变账本。</p></div><div className="flex gap-2"><PriceDialog onSaved={load} /><Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw className="size-4" />刷新</Button></div></header>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={<Building2 className="size-4" />} label="租户" value={String(data.tenants.length)} /><Stat icon={<CreditCard className="size-4" />} label="待审订单" value={String(pending.length)} /><Stat icon={<Tags className="size-4" />} label="有效价格" value={String(data.prices.filter((price) => price.status === "active").length)} /><Stat icon={<Scale className="size-4" />} label="租户余额合计" value={money(balance, "USD")} /><Stat icon={<RefreshCw className="size-4" />} label="未解决告警" value={String(data.alerts.filter((alert) => alert.status === "open").length)} /></div>

        <section className="overflow-x-auto rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">租户</h2></div><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs text-subtle"><tr><th className="px-4 py-3">企业</th><th>状态</th><th>套餐</th><th>现金 / 预留</th><th>套餐额度 / 预留</th><th>计费邮箱</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{data.tenants.map((tenant) => <tr key={String(tenant.id)} className="border-t border-border"><td className="px-4 py-3"><p className="font-medium">{String(tenant.name)}</p><p className="font-mono text-[11px] text-subtle">{String(tenant.slug)}</p></td><td><Badge tone={tenant.status === "active" ? "ok" : tenant.status === "trial" ? "info" : "danger"}>{String(tenant.status)}</Badge></td><td><select className="h-9 rounded-sm border border-border bg-elevated px-2 text-xs" value={String(tenant.pending_plan_id || tenant.plan_id)} onChange={(event) => void changePlan(String(tenant.id), event.target.value, load)}>{data.plans.filter((plan) => plan.status === "active").map((plan) => <option key={String(plan.id)} value={String(plan.id)}>{String(plan.name)}</option>)}</select><p className="mt-1 text-[11px] text-subtle">当前 {String(tenant.plan_id)}{tenant.pending_plan_id ? ` · 下期 ${String(tenant.pending_plan_id)}` : ""}</p></td><td>{money(tenant.balance_minor, tenant.currency)} / {money(tenant.reserved_minor, tenant.currency)}</td><td>{money(tenant.included_balance_minor, tenant.currency)} / {money(tenant.included_reserved_minor, tenant.currency)}</td><td>{String(tenant.billing_email)}</td><td className="text-xs text-muted">{new Date(String(tenant.created_at)).toLocaleString("zh-CN")}</td><td><div className="flex flex-wrap gap-1"><AdjustmentDialog tenant={tenant} onSaved={load} /><Button variant="secondary" size="sm" onClick={() => void settlePlan(String(tenant.id), load)}>结算账期</Button><Button variant="ghost" size="sm" onClick={() => void tenantStatus(String(tenant.id), tenant.status === "suspended" ? "active" : "suspended", load)}>{tenant.status === "suspended" ? "恢复" : "暂停"}</Button></div></td></tr>)}</tbody></table></section>

      <div className="grid gap-6 lg:grid-cols-2">
        <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">待审核人工订单</h2></div><div className="divide-y divide-border">{pending.map((order) => <div key={String(order.id)} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="font-medium">{money(order.amount_minor, order.currency)}</p><p className="text-xs text-subtle">租户 {String(order.tenant_id)} · {new Date(String(order.created_at)).toLocaleString("zh-CN")}</p></div><Button size="sm" onClick={() => void settleOrder(String(order.id), load)}>确认到账</Button></div>)}{!pending.length ? <p className="px-5 py-8 text-center text-sm text-subtle">没有待处理订单</p> : null}</div></section>
        <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">价格版本</h2></div><div className="max-h-96 divide-y divide-border overflow-y-auto">{data.prices.map((price) => <div key={String(price.id)} className="flex items-center justify-between gap-3 px-5 py-3 text-sm"><div><p className="font-medium">{String(price.provider)} · {String(price.model)}</p><p className="text-xs text-subtle">{String(price.capability)} · v{String(price.version)} · markup {Number(price.markup_basis_points || 0) / 100}%</p></div><Badge tone={price.status === "active" ? "ok" : "default"}>{String(price.status)}</Badge></div>)}</div></section>
      </div>
      <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">Stripe 支付与退款</h2><p className="mt-1 text-xs text-subtle">只根据已验签事件入账；对异常订单可从 Stripe 服务端重新对账。</p></div><div className="max-h-96 divide-y divide-border overflow-y-auto">{stripeOrders.map((order) => <div key={String(order.id)} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium">充值 {money(order.amount_minor, order.currency)} · 实付 {money(order.gross_minor || order.amount_minor, order.currency)} · {String(order.status)}</p><p className="font-mono text-[11px] text-subtle">税 {money(order.tax_minor, order.currency)} · {String(order.id)} · {String(order.provider_reference || "尚无支付引用")}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => void reconcileOrder(String(order.id), load)}>服务端对账</Button>{["paid", "partially_refunded"].includes(String(order.status)) ? <RefundDialog order={order} onSaved={load} /> : null}</div></div>)}{!stripeOrders.length ? <p className="px-5 py-8 text-center text-sm text-subtle">暂无 Stripe 订单</p> : null}</div></section>
      <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">支付 Webhook 事件</h2></div><div className="max-h-80 divide-y divide-border overflow-y-auto">{data.paymentEvents.map((event) => <div key={String(event.id)} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium">{String(event.event_type)}</p><p className="font-mono text-[11px] text-subtle">{String(event.provider_event_id)} · 尝试 {String(event.attempt_count)}</p></div><Badge tone={event.status === "processed" || event.status === "ignored" ? "ok" : event.status === "failed" ? "danger" : "warn"}>{String(event.status)}</Badge></div>)}{!data.paymentEvents.length ? <p className="px-5 py-8 text-center text-sm text-subtle">暂无支付事件</p> : null}</div></section>
      <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">拒付与资金撤回</h2></div><div className="max-h-80 divide-y divide-border overflow-y-auto">{data.disputes.map((dispute) => <div key={String(dispute.id)} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium">{money(dispute.amount_minor, dispute.currency)} · {String(dispute.reason)}</p><p className="font-mono text-[11px] text-subtle">{String(dispute.provider_dispute_id)} · 订单 {String(dispute.order_id)}</p></div><Badge tone={dispute.status === "won" || dispute.status === "warning_closed" ? "ok" : dispute.status === "lost" ? "danger" : "warn"}>{String(dispute.status)}</Badge></div>)}{!data.disputes.length ? <p className="px-5 py-8 text-center text-sm text-subtle">暂无拒付</p> : null}</div></section>
      <section className="rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-medium">商业告警</h2></div><div className="max-h-80 divide-y divide-border overflow-y-auto">{data.alerts.map((alert) => <div key={String(alert.id)} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium">{String(alert.code)}</p><p className="text-xs text-subtle">{String(alert.message)} · {new Date(String(alert.last_seen_at)).toLocaleString("zh-CN")}</p></div><Badge tone={alert.status === "open" ? alert.severity === "critical" ? "danger" : "warn" : "ok"}>{String(alert.status)}</Badge></div>)}{!data.alerts.length ? <p className="px-5 py-8 text-center text-sm text-subtle">暂无告警</p> : null}</div></section>
    </div>
  );
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center gap-2 text-xs text-subtle">{icon}{label}</div><p className="mt-3 text-2xl font-medium">{value}</p></div>; }

async function action(body: Record<string, unknown>) {
  const response = await fetch("/api/admin/commercial", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json() as { ok?: boolean; error?: string };
  if (!response.ok || !result.ok) throw new Error(result.error || "操作失败");
}

async function tenantStatus(tenantId: string, status: string, reload: () => Promise<void>) { try { await action({ action: "tenant-status", tenantId, status }); toast.success("租户状态已更新"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "更新失败"); } }
async function changePlan(tenantId: string, planId: string, reload: () => Promise<void>) { try { await action({ action: "tenant-plan", tenantId, planId }); toast.success("套餐变更已安排在下一账期"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "套餐更新失败"); } }
async function settlePlan(tenantId: string, reload: () => Promise<void>) { try { await action({ action: "settle-plan-period", tenantId }); toast.success("套餐账期已幂等结算"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "账期结算失败"); } }
async function settleOrder(orderId: string, reload: () => Promise<void>) { try { await action({ action: "settle-order", orderId }); toast.success("订单已确认到账"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "结算失败"); } }
async function reconcileOrder(orderId: string, reload: () => Promise<void>) { try { await action({ action: "reconcile-payment", orderId }); toast.success("服务端对账完成"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "对账失败"); } }

function RefundDialog({ order, onSaved }: { order: Record<string, unknown>; onSaved: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const refundable = Math.max(0, Number(order.amount_minor || 0) - Number(order.refunded_minor || 0)); const [amount, setAmount] = useState(String(refundable / 100)); const [reason, setReason] = useState("Customer refund");
  async function refund() { try { await action({ action: "refund-order", orderId: order.id, amountMinor: Math.round(Number(amount) * 100), reason, idempotencyKey: crypto.randomUUID() }); toast.success("退款已提交并写入账本"); setOpen(false); await onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "退款失败"); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="destructive">退款</Button></DialogTrigger><DialogContent title="Stripe 退款"><div className="space-y-3"><Field label={`金额（${String(order.currency)}，最多 ${money(refundable, order.currency)}）`}><Input type="number" min="0.01" max={refundable / 100} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></Field><Field label="原因"><Input value={reason} onChange={(event) => setReason(event.target.value)} /></Field><p className="text-xs text-subtle">系统会先冻结等额可用余额，Stripe 成功后再写入不可变退款流水。</p><Button className="w-full" variant="destructive" onClick={() => void refund()}>确认退款</Button></div></DialogContent></Dialog>;
}

function AdjustmentDialog({ tenant, onSaved }: { tenant: Record<string, unknown>; onSaved: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [amount, setAmount] = useState("0"); const [description, setDescription] = useState("Administrator adjustment");
  async function save() { try { await action({ action: "adjust-balance", tenantId: tenant.id, deltaMinor: Math.round(Number(amount) * 100), description, idempotencyKey: crypto.randomUUID() }); toast.success("余额已调整"); setOpen(false); await onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "调整失败"); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="sm"><DollarSign className="size-3.5" />调账</Button></DialogTrigger><DialogContent title={`余额调整 · ${String(tenant.name)}`}><div className="space-y-3"><Field label={`金额（${String(tenant.currency)}，可为负数）`}><Input type="number" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></Field><Field label="原因"><Input value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Button className="w-full" onClick={() => void save()}>提交不可变账务流水</Button></div></DialogContent></Dialog>;
}

function PriceDialog({ onSaved }: { onSaved: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [provider, setProvider] = useState("openai"); const [model, setModel] = useState(""); const [capability, setCapability] = useState("chat"); const [inputRate, setInputRate] = useState("0"); const [outputRate, setOutputRate] = useState("0"); const [imagePrice, setImagePrice] = useState("0"); const [markup, setMarkup] = useState("20");
  async function save() { try { await action({ action: "publish-price", provider, model, capability, currency: "USD", inputMicrosPerMillion: Math.round(Number(inputRate) * 1_000_000), outputMicrosPerMillion: Math.round(Number(outputRate) * 1_000_000), imagePriceMinor: Math.round(Number(imagePrice) * 100), markupBasisPoints: Math.round(Number(markup) * 100) }); toast.success("新价格版本已发布"); setOpen(false); await onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "价格发布失败"); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Tags className="size-4" />发布价格</Button></DialogTrigger><DialogContent title="发布官方模型价格版本"><div className="grid gap-3 sm:grid-cols-2"><Field label="供应商"><Select value={provider} onValueChange={setProvider}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="openai">OpenAI</SelectItem><SelectItem value="google">Google Gemini API</SelectItem><SelectItem value="vertex">Google Vertex AI</SelectItem><SelectItem value="leonardo">Leonardo</SelectItem></SelectContent></Select></Field><Field label="能力"><Select value={capability} onValueChange={setCapability}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="chat">Chat</SelectItem><SelectItem value="image">Image</SelectItem></SelectContent></Select></Field><Field label="官方模型 ID"><Input value={model} onChange={(event) => setModel(event.target.value)} /></Field><Field label="加价率 %"><Input type="number" value={markup} onChange={(event) => setMarkup(event.target.value)} /></Field><Field label="输入 $ / 1M Tokens"><Input type="number" step="0.0001" value={inputRate} onChange={(event) => setInputRate(event.target.value)} /></Field><Field label="输出 $ / 1M Tokens"><Input type="number" step="0.0001" value={outputRate} onChange={(event) => setOutputRate(event.target.value)} /></Field><Field label="每张图片 $"><Input type="number" step="0.01" value={imagePrice} onChange={(event) => setImagePrice(event.target.value)} /></Field></div><Button className="mt-4 w-full" onClick={() => void save()}>发布新版本并停用旧版本</Button></DialogContent></Dialog>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
