/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiRuntimeRouteImport } from './routes/api/runtime'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as InternalReadinessRouteImport } from './routes/internal/readiness'
import { Route as V1ModelsRouteImport } from './routes/v1/models'
import { Route as V1ResponsesRouteImport } from './routes/v1/responses'
import { Route as ApiAccountsProbeRouteImport } from './routes/api/accounts/probe'
import { Route as ApiAdminAccountAnalyticsRouteImport } from './routes/api/admin/account-analytics'
import { Route as ApiAdminAccountChecksRouteImport } from './routes/api/admin/account-checks'
import { Route as ApiAdminAccountInspectionsRouteImport } from './routes/api/admin/account-inspections'
import { Route as ApiAdminAccountOperationsRouteImport } from './routes/api/admin/account-operations'
import { Route as ApiAdminInvokeRouteImport } from './routes/api/admin/invoke'
import { Route as ApiAdminLoginPackRouteImport } from './routes/api/admin/login-pack'
import { Route as ApiAdminMetricsRouteImport } from './routes/api/admin/metrics'
import { Route as ApiAdminPlaneRouteImport } from './routes/api/admin/plane'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminWorkerKitRouteImport } from './routes/api/admin/worker-kit'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiWorkerAccountInspectionsRouteImport } from './routes/api/worker/account-inspections'
import { Route as ApiWorkerChunkRouteImport } from './routes/api/worker/chunk'
import { Route as ApiWorkerControlRouteImport } from './routes/api/worker/control'
import { Route as ApiWorkerMediaRouteImport } from './routes/api/worker/media'
import { Route as ApiWorkerNextRouteImport } from './routes/api/worker/next'
import { Route as ApiWorkerResultRouteImport } from './routes/api/worker/result'
import { Route as V1ChatCompletionsRouteImport } from './routes/v1/chat/completions'
import { Route as V1ImagesEditsRouteImport } from './routes/v1/images/edits'
import { Route as V1ImagesGenerationsRouteImport } from './routes/v1/images/generations'
import { Route as V1betaModelsSplatRouteImport } from './routes/v1beta/models/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeRoute = ApiRuntimeRouteImport.update({
  id: '/api/runtime',
  path: '/api/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalReadinessRoute = InternalReadinessRouteImport.update({
  id: '/internal/readiness',
  path: '/internal/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsRoute = V1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ResponsesRoute = V1ResponsesRouteImport.update({
  id: '/v1/responses',
  path: '/v1/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsProbeRoute = ApiAccountsProbeRouteImport.update({
  id: '/api/accounts/probe',
  path: '/api/accounts/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccountAnalyticsRoute =
  ApiAdminAccountAnalyticsRouteImport.update({
    id: '/api/admin/account-analytics',
    path: '/api/admin/account-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountChecksRoute = ApiAdminAccountChecksRouteImport.update({
  id: '/api/admin/account-checks',
  path: '/api/admin/account-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccountInspectionsRoute =
  ApiAdminAccountInspectionsRouteImport.update({
    id: '/api/admin/account-inspections',
    path: '/api/admin/account-inspections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountOperationsRoute =
  ApiAdminAccountOperationsRouteImport.update({
    id: '/api/admin/account-operations',
    path: '/api/admin/account-operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminInvokeRoute = ApiAdminInvokeRouteImport.update({
  id: '/api/admin/invoke',
  path: '/api/admin/invoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginPackRoute = ApiAdminLoginPackRouteImport.update({
  id: '/api/admin/login-pack',
  path: '/api/admin/login-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMetricsRoute = ApiAdminMetricsRouteImport.update({
  id: '/api/admin/metrics',
  path: '/api/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlaneRoute = ApiAdminPlaneRouteImport.update({
  id: '/api/admin/plane',
  path: '/api/admin/plane',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWorkerKitRoute = ApiAdminWorkerKitRouteImport.update({
  id: '/api/admin/worker-kit',
  path: '/api/admin/worker-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerAccountInspectionsRoute =
  ApiWorkerAccountInspectionsRouteImport.update({
    id: '/api/worker/account-inspections',
    path: '/api/worker/account-inspections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkerChunkRoute = ApiWorkerChunkRouteImport.update({
  id: '/api/worker/chunk',
  path: '/api/worker/chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerControlRoute = ApiWorkerControlRouteImport.update({
  id: '/api/worker/control',
  path: '/api/worker/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerMediaRoute = ApiWorkerMediaRouteImport.update({
  id: '/api/worker/media',
  path: '/api/worker/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerNextRoute = ApiWorkerNextRouteImport.update({
  id: '/api/worker/next',
  path: '/api/worker/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerResultRoute = ApiWorkerResultRouteImport.update({
  id: '/api/worker/result',
  path: '/api/worker/result',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChatCompletionsRoute = V1ChatCompletionsRouteImport.update({
  id: '/v1/chat/completions',
  path: '/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ImagesEditsRoute = V1ImagesEditsRouteImport.update({
  id: '/v1/images/edits',
  path: '/v1/images/edits',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ImagesGenerationsRoute = V1ImagesGenerationsRouteImport.update({
  id: '/v1/images/generations',
  path: '/v1/images/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const V1betaModelsSplatRoute = V1betaModelsSplatRouteImport.update({
  id: '/v1beta/models/$',
  path: '/v1beta/models/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/console': typeof ConsoleRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/playground': typeof PlaygroundRoute
  '/proxies': typeof ProxiesRoute
  '/readyz': typeof ReadyzRoute
  '/settings': typeof SettingsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/usage': typeof ApiUsageRoute
  '/internal/readiness': typeof InternalReadinessRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/api/accounts/probe': typeof ApiAccountsProbeRoute
  '/api/admin/account-analytics': typeof ApiAdminAccountAnalyticsRoute
  '/api/admin/account-checks': typeof ApiAdminAccountChecksRoute
  '/api/admin/account-inspections': typeof ApiAdminAccountInspectionsRoute
  '/api/admin/account-operations': typeof ApiAdminAccountOperationsRoute
  '/api/admin/invoke': typeof ApiAdminInvokeRoute
  '/api/admin/login-pack': typeof ApiAdminLoginPackRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/plane': typeof ApiAdminPlaneRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/worker-kit': typeof ApiAdminWorkerKitRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/worker/account-inspections': typeof ApiWorkerAccountInspectionsRoute
  '/api/worker/chunk': typeof ApiWorkerChunkRoute
  '/api/worker/control': typeof ApiWorkerControlRoute
  '/api/worker/media': typeof ApiWorkerMediaRoute
  '/api/worker/next': typeof ApiWorkerNextRoute
  '/api/worker/result': typeof ApiWorkerResultRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/v1/images/edits': typeof V1ImagesEditsRoute
  '/v1/images/generations': typeof V1ImagesGenerationsRoute
  '/v1beta/models/$': typeof V1betaModelsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/console': typeof ConsoleRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/playground': typeof PlaygroundRoute
  '/proxies': typeof ProxiesRoute
  '/readyz': typeof ReadyzRoute
  '/settings': typeof SettingsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/usage': typeof ApiUsageRoute
  '/internal/readiness': typeof InternalReadinessRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/api/accounts/probe': typeof ApiAccountsProbeRoute
  '/api/admin/account-analytics': typeof ApiAdminAccountAnalyticsRoute
  '/api/admin/account-checks': typeof ApiAdminAccountChecksRoute
  '/api/admin/account-inspections': typeof ApiAdminAccountInspectionsRoute
  '/api/admin/account-operations': typeof ApiAdminAccountOperationsRoute
  '/api/admin/invoke': typeof ApiAdminInvokeRoute
  '/api/admin/login-pack': typeof ApiAdminLoginPackRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/plane': typeof ApiAdminPlaneRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/worker-kit': typeof ApiAdminWorkerKitRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/worker/account-inspections': typeof ApiWorkerAccountInspectionsRoute
  '/api/worker/chunk': typeof ApiWorkerChunkRoute
  '/api/worker/control': typeof ApiWorkerControlRoute
  '/api/worker/media': typeof ApiWorkerMediaRoute
  '/api/worker/next': typeof ApiWorkerNextRoute
  '/api/worker/result': typeof ApiWorkerResultRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/v1/images/edits': typeof V1ImagesEditsRoute
  '/v1/images/generations': typeof V1ImagesGenerationsRoute
  '/v1beta/models/$': typeof V1betaModelsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/console': typeof ConsoleRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/playground': typeof PlaygroundRoute
  '/proxies': typeof ProxiesRoute
  '/readyz': typeof ReadyzRoute
  '/settings': typeof SettingsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/api/usage': typeof ApiUsageRoute
  '/internal/readiness': typeof InternalReadinessRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/api/accounts/probe': typeof ApiAccountsProbeRoute
  '/api/admin/account-analytics': typeof ApiAdminAccountAnalyticsRoute
  '/api/admin/account-checks': typeof ApiAdminAccountChecksRoute
  '/api/admin/account-inspections': typeof ApiAdminAccountInspectionsRoute
  '/api/admin/account-operations': typeof ApiAdminAccountOperationsRoute
  '/api/admin/invoke': typeof ApiAdminInvokeRoute
  '/api/admin/login-pack': typeof ApiAdminLoginPackRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/plane': typeof ApiAdminPlaneRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/worker-kit': typeof ApiAdminWorkerKitRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/worker/account-inspections': typeof ApiWorkerAccountInspectionsRoute
  '/api/worker/chunk': typeof ApiWorkerChunkRoute
  '/api/worker/control': typeof ApiWorkerControlRoute
  '/api/worker/media': typeof ApiWorkerMediaRoute
  '/api/worker/next': typeof ApiWorkerNextRoute
  '/api/worker/result': typeof ApiWorkerResultRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/v1/images/edits': typeof V1ImagesEditsRoute
  '/v1/images/generations': typeof V1ImagesGenerationsRoute
  '/v1beta/models/$': typeof V1betaModelsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/console'
    | '/healthz'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/playground'
    | '/proxies'
    | '/readyz'
    | '/settings'
    | '/api/jobs'
    | '/api/keys'
    | '/api/ready'
    | '/api/runtime'
    | '/api/usage'
    | '/internal/readiness'
    | '/v1/models'
    | '/v1/responses'
    | '/api/accounts/probe'
    | '/api/admin/account-analytics'
    | '/api/admin/account-checks'
    | '/api/admin/account-inspections'
    | '/api/admin/account-operations'
    | '/api/admin/invoke'
    | '/api/admin/login-pack'
    | '/api/admin/metrics'
    | '/api/admin/plane'
    | '/api/admin/session'
    | '/api/admin/worker-kit'
    | '/api/media/$id'
    | '/api/worker/account-inspections'
    | '/api/worker/chunk'
    | '/api/worker/control'
    | '/api/worker/media'
    | '/api/worker/next'
    | '/api/worker/result'
    | '/v1/chat/completions'
    | '/v1/images/edits'
    | '/v1/images/generations'
    | '/v1beta/models/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/console'
    | '/healthz'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/playground'
    | '/proxies'
    | '/readyz'
    | '/settings'
    | '/api/jobs'
    | '/api/keys'
    | '/api/ready'
    | '/api/runtime'
    | '/api/usage'
    | '/internal/readiness'
    | '/v1/models'
    | '/v1/responses'
    | '/api/accounts/probe'
    | '/api/admin/account-analytics'
    | '/api/admin/account-checks'
    | '/api/admin/account-inspections'
    | '/api/admin/account-operations'
    | '/api/admin/invoke'
    | '/api/admin/login-pack'
    | '/api/admin/metrics'
    | '/api/admin/plane'
    | '/api/admin/session'
    | '/api/admin/worker-kit'
    | '/api/media/$id'
    | '/api/worker/account-inspections'
    | '/api/worker/chunk'
    | '/api/worker/control'
    | '/api/worker/media'
    | '/api/worker/next'
    | '/api/worker/result'
    | '/v1/chat/completions'
    | '/v1/images/edits'
    | '/v1/images/generations'
    | '/v1beta/models/$'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/console'
    | '/healthz'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/playground'
    | '/proxies'
    | '/readyz'
    | '/settings'
    | '/api/jobs'
    | '/api/keys'
    | '/api/ready'
    | '/api/runtime'
    | '/api/usage'
    | '/internal/readiness'
    | '/v1/models'
    | '/v1/responses'
    | '/api/accounts/probe'
    | '/api/admin/account-analytics'
    | '/api/admin/account-checks'
    | '/api/admin/account-inspections'
    | '/api/admin/account-operations'
    | '/api/admin/invoke'
    | '/api/admin/login-pack'
    | '/api/admin/metrics'
    | '/api/admin/plane'
    | '/api/admin/session'
    | '/api/admin/worker-kit'
    | '/api/media/$id'
    | '/api/worker/account-inspections'
    | '/api/worker/chunk'
    | '/api/worker/control'
    | '/api/worker/media'
    | '/api/worker/next'
    | '/api/worker/result'
    | '/v1/chat/completions'
    | '/v1/images/edits'
    | '/v1/images/generations'
    | '/v1beta/models/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ConsoleRoute: typeof ConsoleRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProxiesRoute: typeof ProxiesRoute
  ReadyzRoute: typeof ReadyzRoute
  SettingsRoute: typeof SettingsRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiRuntimeRoute: typeof ApiRuntimeRoute
  ApiUsageRoute: typeof ApiUsageRoute
  InternalReadinessRoute: typeof InternalReadinessRoute
  V1ModelsRoute: typeof V1ModelsRoute
  V1ResponsesRoute: typeof V1ResponsesRoute
  ApiAccountsProbeRoute: typeof ApiAccountsProbeRoute
  ApiAdminAccountAnalyticsRoute: typeof ApiAdminAccountAnalyticsRoute
  ApiAdminAccountChecksRoute: typeof ApiAdminAccountChecksRoute
  ApiAdminAccountInspectionsRoute: typeof ApiAdminAccountInspectionsRoute
  ApiAdminAccountOperationsRoute: typeof ApiAdminAccountOperationsRoute
  ApiAdminInvokeRoute: typeof ApiAdminInvokeRoute
  ApiAdminLoginPackRoute: typeof ApiAdminLoginPackRoute
  ApiAdminMetricsRoute: typeof ApiAdminMetricsRoute
  ApiAdminPlaneRoute: typeof ApiAdminPlaneRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminWorkerKitRoute: typeof ApiAdminWorkerKitRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiWorkerAccountInspectionsRoute: typeof ApiWorkerAccountInspectionsRoute
  ApiWorkerChunkRoute: typeof ApiWorkerChunkRoute
  ApiWorkerControlRoute: typeof ApiWorkerControlRoute
  ApiWorkerMediaRoute: typeof ApiWorkerMediaRoute
  ApiWorkerNextRoute: typeof ApiWorkerNextRoute
  ApiWorkerResultRoute: typeof ApiWorkerResultRoute
  V1ChatCompletionsRoute: typeof V1ChatCompletionsRoute
  V1ImagesEditsRoute: typeof V1ImagesEditsRoute
  V1ImagesGenerationsRoute: typeof V1ImagesGenerationsRoute
  V1betaModelsSplatRoute: typeof V1betaModelsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime': {
      id: '/api/runtime'
      path: '/api/runtime'
      fullPath: '/api/runtime'
      preLoaderRoute: typeof ApiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/readiness': {
      id: '/internal/readiness'
      path: '/internal/readiness'
      fullPath: '/internal/readiness'
      preLoaderRoute: typeof InternalReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models': {
      id: '/v1/models'
      path: '/v1/models'
      fullPath: '/v1/models'
      preLoaderRoute: typeof V1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/responses': {
      id: '/v1/responses'
      path: '/v1/responses'
      fullPath: '/v1/responses'
      preLoaderRoute: typeof V1ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/probe': {
      id: '/api/accounts/probe'
      path: '/api/accounts/probe'
      fullPath: '/api/accounts/probe'
      preLoaderRoute: typeof ApiAccountsProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/account-analytics': {
      id: '/api/admin/account-analytics'
      path: '/api/admin/account-analytics'
      fullPath: '/api/admin/account-analytics'
      preLoaderRoute: typeof ApiAdminAccountAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/account-checks': {
      id: '/api/admin/account-checks'
      path: '/api/admin/account-checks'
      fullPath: '/api/admin/account-checks'
      preLoaderRoute: typeof ApiAdminAccountChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/account-inspections': {
      id: '/api/admin/account-inspections'
      path: '/api/admin/account-inspections'
      fullPath: '/api/admin/account-inspections'
      preLoaderRoute: typeof ApiAdminAccountInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/account-operations': {
      id: '/api/admin/account-operations'
      path: '/api/admin/account-operations'
      fullPath: '/api/admin/account-operations'
      preLoaderRoute: typeof ApiAdminAccountOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invoke': {
      id: '/api/admin/invoke'
      path: '/api/admin/invoke'
      fullPath: '/api/admin/invoke'
      preLoaderRoute: typeof ApiAdminInvokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login-pack': {
      id: '/api/admin/login-pack'
      path: '/api/admin/login-pack'
      fullPath: '/api/admin/login-pack'
      preLoaderRoute: typeof ApiAdminLoginPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/metrics': {
      id: '/api/admin/metrics'
      path: '/api/admin/metrics'
      fullPath: '/api/admin/metrics'
      preLoaderRoute: typeof ApiAdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/plane': {
      id: '/api/admin/plane'
      path: '/api/admin/plane'
      fullPath: '/api/admin/plane'
      preLoaderRoute: typeof ApiAdminPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/worker-kit': {
      id: '/api/admin/worker-kit'
      path: '/api/admin/worker-kit'
      fullPath: '/api/admin/worker-kit'
      preLoaderRoute: typeof ApiAdminWorkerKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/account-inspections': {
      id: '/api/worker/account-inspections'
      path: '/api/worker/account-inspections'
      fullPath: '/api/worker/account-inspections'
      preLoaderRoute: typeof ApiWorkerAccountInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/chunk': {
      id: '/api/worker/chunk'
      path: '/api/worker/chunk'
      fullPath: '/api/worker/chunk'
      preLoaderRoute: typeof ApiWorkerChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/control': {
      id: '/api/worker/control'
      path: '/api/worker/control'
      fullPath: '/api/worker/control'
      preLoaderRoute: typeof ApiWorkerControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/media': {
      id: '/api/worker/media'
      path: '/api/worker/media'
      fullPath: '/api/worker/media'
      preLoaderRoute: typeof ApiWorkerMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/next': {
      id: '/api/worker/next'
      path: '/api/worker/next'
      fullPath: '/api/worker/next'
      preLoaderRoute: typeof ApiWorkerNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/result': {
      id: '/api/worker/result'
      path: '/api/worker/result'
      fullPath: '/api/worker/result'
      preLoaderRoute: typeof ApiWorkerResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/chat/completions': {
      id: '/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/v1/chat/completions'
      preLoaderRoute: typeof V1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/images/edits': {
      id: '/v1/images/edits'
      path: '/v1/images/edits'
      fullPath: '/v1/images/edits'
      preLoaderRoute: typeof V1ImagesEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/images/generations': {
      id: '/v1/images/generations'
      path: '/v1/images/generations'
      fullPath: '/v1/images/generations'
      preLoaderRoute: typeof V1ImagesGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1beta/models/$': {
      id: '/v1beta/models/$'
      path: '/v1beta/models/$'
      fullPath: '/v1beta/models/$'
      preLoaderRoute: typeof V1betaModelsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ConsoleRoute: ConsoleRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProxiesRoute: ProxiesRoute,
  ReadyzRoute: ReadyzRoute,
  SettingsRoute: SettingsRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiRuntimeRoute: ApiRuntimeRoute,
  ApiUsageRoute: ApiUsageRoute,
  InternalReadinessRoute: InternalReadinessRoute,
  V1ModelsRoute: V1ModelsRoute,
  V1ResponsesRoute: V1ResponsesRoute,
  ApiAccountsProbeRoute: ApiAccountsProbeRoute,
  ApiAdminAccountAnalyticsRoute: ApiAdminAccountAnalyticsRoute,
  ApiAdminAccountChecksRoute: ApiAdminAccountChecksRoute,
  ApiAdminAccountInspectionsRoute: ApiAdminAccountInspectionsRoute,
  ApiAdminAccountOperationsRoute: ApiAdminAccountOperationsRoute,
  ApiAdminInvokeRoute: ApiAdminInvokeRoute,
  ApiAdminLoginPackRoute: ApiAdminLoginPackRoute,
  ApiAdminMetricsRoute: ApiAdminMetricsRoute,
  ApiAdminPlaneRoute: ApiAdminPlaneRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminWorkerKitRoute: ApiAdminWorkerKitRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiWorkerAccountInspectionsRoute: ApiWorkerAccountInspectionsRoute,
  ApiWorkerChunkRoute: ApiWorkerChunkRoute,
  ApiWorkerControlRoute: ApiWorkerControlRoute,
  ApiWorkerMediaRoute: ApiWorkerMediaRoute,
  ApiWorkerNextRoute: ApiWorkerNextRoute,
  ApiWorkerResultRoute: ApiWorkerResultRoute,
  V1ChatCompletionsRoute: V1ChatCompletionsRoute,
  V1ImagesEditsRoute: V1ImagesEditsRoute,
  V1ImagesGenerationsRoute: V1ImagesGenerationsRoute,
  V1betaModelsSplatRoute: V1betaModelsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
